import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  navbarOuter: {
    width: '100%',
    backgroundColor: '#12131A',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    zIndex: 10000,
    position: 'relative',
    ...Platform.select({
      web: {
        position: 'sticky',
        top: 0,
        backdropFilter: 'blur(12px)',
        backgroundColor: 'rgba(18, 19, 26, 0.85)',
      } as any,
    }),
  },
  navbarHeader: {
    maxWidth: 1200,
    width: '100%',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  brand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoPokeBall: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoPokeBallTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: '#FF3E3E',
  },
  logoPokeBallBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: '#FFFFFF',
  },
  logoPokeBallCenter: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#303030',
    zIndex: 10,
  },
  brandText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  brandTextRed: {
    color: '#FF3E3E',
  },
  desktopUserPreview: {
    ...Platform.select({
      web: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.03)',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
      } as any,
      default: {
        display: 'none',
      },
    }),
  },
  desktopUserName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  desktopUserStats: {
    color: '#8B949E',
    fontSize: 11,
    fontWeight: '600',
  },
  avatarBorderMini: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1E202B',
    overflow: 'hidden',
  },
  avatarMiniImage: {
    width: 32,
    height: 32,
    marginTop: 2,
  },
  hamburgerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    gap: 8,
    ...Platform.select({
      web: {
        cursor: 'pointer',
        transition: 'all 0.2s ease',
      } as any,
    }),
  },
  hamburgerBtnOpen: {
    borderColor: '#FF3E3E',
    backgroundColor: 'rgba(255, 62, 62, 0.1)',
  },
  hamburgerLabel: {
    color: '#E6EDF3',
    fontSize: 12,
    fontWeight: '700',
  },
  menuPokeBall: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    ...Platform.select({
      web: {
        transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      } as any,
    }),
  },
  menuPokeBallActive: {
    transform: [{ rotate: '180deg' }],
  },
  menuPokeBallTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: '#FF3E3E',
  },
  menuPokeBallBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: '#FFFFFF',
  },
  menuPokeBallCenter: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#303030',
    zIndex: 10,
  },
  dropdownContainer: {
    position: 'absolute',
    top: '100%',
    right: 0,
    left: 0,
    backgroundColor: '#12131A',
    borderBottomWidth: 2,
    borderBottomColor: '#FF3E3E',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 9999,
  },
  dropdownInner: {
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
    padding: 20,
    gap: 16,
  },
  dropdownProfileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    padding: 16,
    gap: 16,
  },
  avatarBorderLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1E202B',
  },
  avatarInnerContainerLarge: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#252836',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarLargeImage: {
    width: 56,
    height: 56,
    marginTop: 4,
  },
  dropdownProfileInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  trainerName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  trainerRank: {
    color: '#FF3E3E',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginTop: 1,
  },
  trainerStats: {
    color: '#8B949E',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  menuLinks: {
    gap: 8,
  },
  menuLinkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
    position: 'relative',
    ...Platform.select({
      web: {
        transition: 'all 0.2s ease',
        cursor: 'pointer',
      } as any,
    }),
  },
  menuLinkItemActive: {
    backgroundColor: 'rgba(255, 62, 62, 0.08)',
    borderColor: 'rgba(255, 62, 62, 0.25)',
  },
  menuIconImage: {
    width: 24,
    height: 24,
  },
  menuLinkLabel: {
    color: '#8B949E',
    fontSize: 15,
    fontWeight: '700',
  },
  menuLinkLabelActive: {
    color: '#FF3E3E',
  },
  activeDot: {
    position: 'absolute',
    right: 16,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF3E3E',
    shadowColor: '#FF3E3E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
  },
  menuLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 62, 62, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 62, 62, 0.15)',
    borderRadius: 12,
    paddingVertical: 12,
    gap: 8,
    marginTop: 8,
    ...Platform.select({
      web: {
        cursor: 'pointer',
        transition: 'all 0.2s ease',
      } as any,
    }),
  },
  logoutIconImage: {
    width: 20,
    height: 20,
  },
  menuLogoutText: {
    color: '#FF6464',
    fontSize: 14,
    fontWeight: '700',
  },
});
